### ISSUE TITLE
Listing sessions

### ISSUE THREAD

**Issue by pushist1y** [aspnet/Session#133]
Is there any conventional way to list all active sessions/session keys? As far as i can say looking into the sources, there is no external access to session keys. Is this by desing or there was no such needs before?

The usecase for that could be enumerating currently online users or forcefully logging off particular user or many other options. 

Should I implement such functionality and offer a pull request?

**Comment by hishamco** [comment]
AFAIK the Identity & Authentication middleware is the best choice for your case, I'm not sure if there's a proper reason to list the active session(s)
/cc @Tracher

**Comment by Tratcher** [comment]
This is by design, the keys contain no meaningful information and we haven't heard any relevant use cases yet.

Remember that browser sessions != users. Users should be tracked by auth cookies (See UseCookieAuthentication in Security). There is a single-sign-out feature that can invalidate auth cookies, see CookieAuthenticationEvents.ValidatePrincipal. The Identity framework hooks into this API to expose the feature.
