### ISSUE TITLE
Allow different formats (JSON in particular)

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Session#142]
It looks like `ISession` is using `byte[]`, which I worry might be forcing premature serialization of data in a way I can't control.

If I wanted to consume this data from another language (shared sessions between servers), it would have to implement this exact same custom format as well as have a way to deserialize the bytes from a .net specific representation.

What would be nicer is if I could tell ASP.net to write the session as a JSON string.  Then anything with access to the shared storage point could read the data.

**Comment by Tratcher** [comment]
The overall session serialization can be controlled by ISessionStore and ISession, but this does not extend to value serialization. You can serialize it to JSON, though admittedly JSON does not have a good way to represent byte[] values.

Trying to serialize arbitrary values as JSON would have the same issues as trying to serialize them as bytes, which is why we opted to move the value serialization mechanics out of the session implementation.

**Comment by atrauzzi** [comment]
So I decided to dive a little into the internals over the weekend and made this: https://github.com/atrauzzi/praxis/tree/master/Praxis/Session/Json

And this: https://github.com/atrauzzi/praxis/blob/master/Praxis/Authentication/JsonTicketSerializer.cs

I'm not a huge fan of the serialzation/reserialization going on due to the `byte[]`, but I understand why and it works.  This leaves me confident that my sessions and tickets are in a portable format.

Feel free to make any comments, but I'll close this for now.  I've got other fish to fry elsewhere in the ASP.net stack ;)
