### ISSUE TITLE
Possible session state race condition

### ISSUE THREAD

**Issue by wanton7** [aspnet/Session#60]
Isn't there a possible race condition in session middleware?

Example if I would send two simultaneous ajax requests both modifying session first would set key called "key1" and second would set key called "key2".
Because there are no locks there is big possibility that only one of the keys would be set. If both would load the session and then last request to call CommitAsync would overwrite other request's modified session state.

This was handled by previous Asp.Net by only allowing one request with writable session for one session id at a time.
That solution wasn't very good performance.

Better solution would be have some sort of session update scope that would lock then load current session state for you to modify and after scope ends it would commit changes and unlock.

If that is too big of a change you should atleast fix current implementation so that setting single key only overwrites that key and not the whole session state.

**Comment by Tratcher** [comment]
All of your observations are correct, and this is the intentional design.  In previous versions of ASP.NET locking the session caused crippling problems with parallel request processing, especially across multiple servers. The new design acknowledges the lossy nature of sessions and does not attempt any concurrency guarantees (except non-corruption).

Serializing all of the values together as a coherent session helps avoid inconsistencies between related keys. We may eventually provide an alternate implementation for incoherent sessions (e.g. each key cached separately). This could also be provided by the community.

Note session will always have an initial race condition if multiple requests are made before the session cookie is set on the client. Each of those parallel requests may create its own session and cookie and then the browser will only keep the last one.

**Comment by wanton7** [comment]
It's true that there could be a race condition when session is first created, but usually it's a page load that creates session and not an ajax call so it's highly unlikely.

Locked update scope would allow to keep multiple related keys consistent and also allow you to even increase a session based counter correctly if session state was refreshed after lock was taken.

In our company's software we do lot of session updates via ajax. When we move to new Asp.Net we probably have to write our own session store to avoid this situation.
It's really great that with this new middleware system we can do that easily.
