### ISSUE TITLE
Secure Coding Compliance

### ISSUE THREAD

**Issue by tienod** [aspnet/Session#76]
Hello,

we need to be compliant with various secure coding standards (and non-disclosure secure coding requirements) as for example the OWASP ASVS3.0.

I miss convenient methods to acheive
a) session id regeneration
b) access to the session id
c) "secure" cookie attribute.

If i simply missed them please point me there. Otherwise i would be glad to know the plans on these topics.

**Comment by Eilon** [comment]
@blowdart ?

**Comment by Tratcher** [comment]
For C use https://github.com/aspnet/HttpAbstractions/issues/42

**Comment by blowdart** [comment]
We've never supported, easily, session regeneration, mainly because our auth process is separate to session and so it's not been a security concern. As we don't support URL based session IDs preloaded session attacks/session fixation isn't a problem.

Secure session cookies are now automatically turned on as soon as you use HTTPS, and you can't downgrade because of security concerns.

Getting the session ID isn't a security concern, so I have no opinion.

@tienod What sort of attacks are you worried about, and what do you believe you need to protect against them? Checklists, like some automated scanners, don't take some framework decisions into account and so flag up false positives. Session fixation is a good example of this - there's never been a real need to do it in ASP.NET

**Comment by Tratcher** [comment]
For A, you cannot reliably regenerate a session ID because it's stored on the client. We recommend clearing the contents of the session via Session.Clear().

For B) we intentionally do not expose the session ID to the application for reasons such as mentioned above, it is an implementation detail. Applications that want to have their own session ID are recommended to store that value in the session.

**Comment by tienod** [comment]
@Tratcher Thanks for C, completely overlooked that.

@blowdart Thanks for clarification. I was assuming that session == auth session. 

It just confused me, that Microsoft.AspNet.Session does not comply with OWASP ASVS 3.0, in requirement 3.7, a session and session id regeneration is required at every occurance of any authentication. ( https://www.owasp.org/images/6/67/OWASPApplicationSecurityVerificationStandard3.0.pdf )
Or the Microsoft Security Development Lifecycle Process 5.2 ( https://www.microsoft.com/en-us/download/confirmation.aspx?id=29884 - page 29)

Have to go to other repo to find the droids I'm looking for.

Thanks and kudos for the great work!

**Comment by blowdart** [comment]
Yea as session holds no with information it's never been necessary to recycle sessions. Lots of updates scanning tools bitch about though.

**Comment by Tratcher** [comment]
Microsoft.AspNet.Authentication.Cookies is used to manage auth sessions. See https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Cookies/CookieAppBuilderExtensions.cs#L19
